#!/bin/bash
echo "What would you name your project?"
read appName
express --no-view $appName
cd $appName
git init

# install default dependencies
npm install nodemon@1.18 chai@4.1 chai-http@4.0 dotenv@6.0 forever@0.15 mocha@5.2 request@2.87 md5@2.2 http-errors@1.7 moment@2.22 body-parser@1.18 od-utility --save
npm audit fix

# create default dir and files
mkdir tests
mkdir helpers
mkdir actions
mkdir middlewares
touch README.md .env
touch CHANGELOG.md

# write client name to env file
echo "Enter your front project name: "
read clientName
echo "CLIENT_NAME=$clientName" >> .env

# add project code to package json
echo "What is your project code: "
read projectCode
touch package.json.tmp
touch package.json.tmp2
brew install jq
jq --arg key $appName  '.name=$key' package.json > package.json.tmp
jq --arg key "nodemon bin/www" '.scripts=(.scripts + {"dev":$key})' package.json > package.json.tmp
jq --arg key $projectCode  '.project_code=$key' package.json.tmp > package.json.tmp2
rm package.json
rm package.json.tmp
mv package.json.tmp2 package.json


# replace app.js
rm app.js
curl -o app.js https://raw.githubusercontent.com/540376482yzb/react-express-back/master/app.js

# download gitignore
curl -o .gitignore https://raw.githubusercontent.com/540376482yzb/react-express-back/master/gitignore

#ignore front end project dir
echo  "
# ingore client name 
$clientName" >> .gitignore

# add a title to README
echo "# ${appName}" >> README.md

# clean out the default route implementation
rm -rf routes
mkdir routes
mkdir routes/v0
mkdir routes/v1
cd routes
curl -o api.route.js https://raw.githubusercontent.com/540376482yzb/react-express-back/master/routes/api.route.js
cd v0/
curl -o index.route.js https://raw.githubusercontent.com/540376482yzb/react-express-back/master/routes/v0/index.route.js
cd ..
cd v1/
curl -o index.route.js https://raw.githubusercontent.com/540376482yzb/react-express-back/master/routes/v1/index.route.js
cd ..
cd ..
npm install

# create front end project
npx create-react-app $clientName

exit 0
