#!/bin/bash
echo "What would you name your project?"
read appName
express --no-view $appName
cd $appName
git init

# create default dir and files
mkdir tests
touch tests/index.js
mkdir helpers
touch helpers/index.js
mkdir actions
touch actions/index.js
mkdir middlewares
touch middlewares/index.js
touch README.md .env
touch CHANGELOG.md

# write client name to env file
echo "Enter your front project name: "
read clientName
echo "CLIENT_NAME=$clientName" >> .env

# rm package-lock.json
# touch package.json.tmp
# touch package.json.tmp2
# brew install jq
# jq --arg key $appName  '.name=$key' package.json > package.json.tmp
# jq --arg key "nodemon bin/www" '.scripts=(.scripts + {"dev":$key})' package.json > package.json.tmp
# jq --arg key $projectCode  '.project_code=$key' package.json.tmp > package.json.tmp2
# rm package.json
# rm package.json.tmp
# mv package.json.tmp2 package.json


# replace app.js
rm app.js
curl -o app.js https://raw.githubusercontent.com/540376482yzb/react-express-back/master/app.js

# download gitignore
curl -o .gitignore https://raw.githubusercontent.com/540376482yzb/react-express-back/master/gitignore

#ignore front end project dir
echo  "
# ingore client name 
$clientName" >> .gitignore

# add a title to README
echo "# ${appName}" >> README.md

# clean out the default route implementation
rm -rf routes
mkdir routes
mkdir routes/v0
mkdir routes/v1
cd routes
curl -o api.route.js https://raw.githubusercontent.com/540376482yzb/react-express-back/master/routes/api.route.js
cd v0/
curl -o index.route.js https://raw.githubusercontent.com/540376482yzb/react-express-back/master/routes/v0/index.route.js
cd ..
cd v1/
curl -o index.route.js https://raw.githubusercontent.com/540376482yzb/react-express-back/master/routes/v1/index.route.js
cd ..
cd ..

# install default dependencies
npm install nodemon dotenv request md5 moment body-parse od-utility --save

exit 0
